#!/usr/bin/env python3
import os
import sqlite3
import argparse
import shutil
import time

def export_cookies(sqlite_file, output_file):
    if not os.path.exists(sqlite_file):
        raise FileNotFoundError(f"No such file: {sqlite_file}")

    # copy the database in case Firefox has it locked
    temp_db = sqlite_file + f".copy_{int(time.time())}"
    shutil.copy2(sqlite_file, temp_db)

    conn = sqlite3.connect(temp_db)
    cursor = conn.cursor()
    cursor.execute("SELECT host, isSecure, path, expiry, name, value FROM moz_cookies")

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# Generated by cookies_exporter.py\n\n")
        for host, is_secure, path, expiry, name, value in cursor.fetchall():
            secure_flag = "TRUE" if is_secure else "FALSE"
            f.write("\t".join([
                host,
                secure_flag,
                path,
                secure_flag,  # placeholder for HTTPOnly
                str(expiry),
                name,
                value
            ]) + "\n")

    conn.close()
    os.remove(temp_db)
    print(f"Exported cookies to {output_file}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export Firefox cookies from a sqlite file to cookies.txt")
    parser.add_argument("sqlite_file", help="Path to cookies.sqlite")
    parser.add_argument("--output", "-o", default="cookies.txt", help="Output file path")
    args = parser.parse_args()

    export_cookies(args.sqlite_file, args.output)
