import os
import sqlite3
import argparse
import shutil
import time
import sys

def export_cookies(sqlite_file, output_file):
    if not os.path.exists(sqlite_file):
        raise FileNotFoundError(f"No such file: {sqlite_file}")

    # copy DB to avoid lock
    temp_db = sqlite_file + f".copy_{int(time.time())}"
    shutil.copy2(sqlite_file, temp_db)

    conn = None
    try:
        conn = sqlite3.connect(temp_db)
        cursor = conn.cursor()

        cursor.execute("SELECT host, path, expiry, name, value, isSecure FROM moz_cookies")

        with open(output_file, "w", encoding="utf-8") as f:
            f.write("# Netscape HTTP Cookie File\n")
            f.write("# Generated by cookies_exporter.py\n\n")
            for host, path, expiry, name, value, isSecure in cursor.fetchall():
                # include subdomains if host starts with .
                include_subdomains = "TRUE" if host.startswith('.') else "FALSE"
                secure_flag = "TRUE" if isSecure else "FALSE"
                expiry_str = str(int(expiry)) if expiry else "0"
                line = "\t".join([
                    host,
                    include_subdomains,
                    path,
                    secure_flag,
                    expiry_str,
                    name or "",
                    value or ""
                ]) + "\n"
                f.write(line)

        print(f"Exported cookies to {output_file}")

    finally:
        if conn:
            conn.close()
        try:
            os.remove(temp_db)
        except Exception:
            pass

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export Firefox cookies from sqlite to cookies.txt")
    parser.add_argument("sqlite_file", help="Path to cookies.sqlite")
    parser.add_argument("--output", "-o", default="cookies.txt", help="Output file path")
    args = parser.parse_args()

    try:
        export_cookies(args.sqlite_file, args.output)
    except Exception as e:
        print("Error:", e, file=sys.stderr)
        sys.exit(1)
